RoutineList
maengoose/routinary pull request #6
Opened 2022-06-28 05:27 UTC by hxunz

루틴 리스트 시간순으로 정렬 했습니다.

시간에 따라서 루틴 제목 앞에 아이콘 변경 예정입니다.
☀️ 해 떠있는 동안 (일출 이후)
🌙 해 져있는 동안 (일몰 이후)

2022-06-30 02:28 UTC, Kihyun92 requested changes
👍🏼

2022-06-30 02:28 UTC, Kihyun92 commented on src/pages/DailyRoutines/DailyRoutines.tsx
> +const insertionSort = (arr: any[]) => {
Routine[] 으로 하면 될것같아요. any 타입은 가능하면 절대 사용하면 안됩니다.

2022-06-30 02:28 UTC, Kihyun92 commented on src/pages/DailyRoutines/DailyRoutines.tsx
> +};
routines 를 직접 조작하고 있는 것 같아요. 원본 배열을 직접 조작하지 않고 map을 사용해서 새로운 배열을 반환하는게 좋을 것 같습니다.

2022-06-30 02:28 UTC, Kihyun92 commented on src/pages/Home/style.ts
> +  font-weight: lighter;
파일 맨 끝에는 공백 추가해주세요.

2022-06-30 02:28 UTC, Kihyun92 commented on .firebase/hosting.YnVpbGQ.cache
> +asset-manifest.json,1656484482482,17d555ddb79fc0ba08cad63445bdb68137ed3b51954ff39ffd46db72800bdc97
이 파일이 깃에 포함되는게 맞나요? 확인해주시고 git으로 관리하지 않아야한다면 gitignore 에 추가해주세요

2022-06-30 02:28 UTC, Kihyun92 commented on src/components/DailyRoutine/DailyRoutine.tsx
> +      }
```suggestion
      {
        <Styled.RoutineInfo isChecked={completed}>
          {startTime} {(startTime >= '05:00' && startTime <= '19:00') ? 🌞 : 🌚} {title} {time}min
        </Styled.RoutineInfo>
      }
```
실제 변하는 부분에 예외처리를 해주는게 좋을 것 같네요.

2022-06-30 05:35 UTC, hxunz commented on src/components/DailyRoutine/DailyRoutine.tsx
> +      }
실제 변하는 부분이 뭔가요,?

2022-06-30 08:20 UTC, Kihyun92 commented on src/components/DailyRoutine/DailyRoutine.tsx
> +      }
저 예외처리를 통해 실제로 화면이 변하는 부분을 의미했습니다~ 여기선 이모티지가 해당하겠네요.

2022-06-30 08:21 UTC, Kihyun92 commented on src/components/DailyRoutine/DailyRoutine.tsx
> +      {(startTime >= '05:00' && startTime <= '19:00') ?
'05:00', '19:00' 이런 부분은 상수로 관리해도 좋을 것 같아요.

```javascript
const SUNRISE = '05:00';
const SUNSET = '19:00';
```

2022-07-05 10:49 UTC, Kihyun92 commented
이거 어떻게 진행중인가요?

2022-07-06 05:54 UTC, hxunz commented
> 이거 어떻게 진행중인가요?

자정이 되면 루틴 해제 시키는 부분과 루틴 리스트의 시간, 내용, 버튼 아이콘들의 위치를 정렬시키는 부분을 구현중입니다.

2022-07-09 10:10 UTC, Kihyun92 approved these changes

2022-07-09 10:10 UTC, merged